# Generated by Django 4.2.24 on 2025-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_check", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("HR", "HR"), ("EMPLOYEE", "Employee")],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
