# Generated by Django 4.2.24 on 2025-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance_check", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facedata",
            name="images",
        ),
        migrations.AlterField(
            model_name="facedata",
            name="embeddings",
            field=models.JSONField(),
        ),
    ]
